### ISSUE TITLE
iOS build fails on v2.4.1: use of undeclared identifier 'memset_s' in AESCrypt.cpp (CocoaPods, Xcode 26)

### ISSUE THREAD

**Issue by forimbajosh21** [Tencent/MMKV#1675]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV

Objective-C++ / C++ (MMKVCore pod, consumed through react-native-mmkv in a React Native app)

### The version of MMKV

v2.4.1 (latest, released 2026-07-30) — this is a **build-time regression introduced in 2.4.1**; v2.4.0 compiles fine in the identical project.

### The platform of MMKV

iOS (Xcode 26.0, iphoneos26.0 SDK, arm64 Release/archive build)

### The installation of MMKV

CocoaPods (`MMKVCore` resolved transitively via `react-native-mmkv` → `MMKV >= 1.3.3`), with `use_frameworks! :linkage => :static`

### What's the issue?

`MMKVCore` 2.4.1 fails to compile:

```
/Users/builder/clone/ios/Pods/MMKVCore/Core/aes/AESCrypt.cpp:83:11: error: use of undeclared identifier 'memset_s'
   83 |     (void)memset_s(ptr, len, 0, len);
      |           ^
1 error generated.
```

Workaround we're using meanwhile: pinning `MMKV`/`MMKVCore` to 2.4.0.

### What's the log of MMKV when that happened?
Not applicable. Full compiler invocation and error from the Xcode build log:

```
CompileC .../MMKVCore.build/Objects-normal/arm64/AESCrypt.o /Users/builder/clone/ios/Pods/MMKVCore/Core/aes/AESCrypt.cpp normal arm64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler

/Applications/Xcode-26.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c++ ... -include /Users/builder/clone/ios/Pods/Target Support Files/MMKVCore/MMKVCore-prefix.pch ... -c /Users/builder/clone/ios/Pods/MMKVCore/Core/aes/AESCrypt.cpp -o .../AESCrypt.o

/Users/builder/clone/ios/Pods/MMKVCore/Core/aes/AESCrypt.cpp:83:11: error: use of undeclared identifier 'memset_s'
   83 |     (void)memset_s(ptr, len, 0, len);
      |           ^
1 error generated.
```

Environment: Xcode 26.0 (Build 17A400), iOS SDK 26.0, CocoaPods, React Native 0.79.7 / Expo SDK 53 prebuild, reproduces 100% on a clean pod install (Codemagic CI). Same project builds fine with MMKV/MMKVCore 2.4.0.

**Comment by lingol** [comment]
That's strange. How does the file look around line 176 in your iOS SDK's `usr/include/_string.h`? It should looks like this, which provides `memset_s()`.
```cpp
/* C11 Annex K */

#if defined(__STDC_WANT_LIB_EXT1__) && __STDC_WANT_LIB_EXT1__ >= 1
#include <sys/_types/_rsize_t.h>
#include <sys/_types/_errno_t.h>

__BEGIN_DECLS
errno_t	memset_s(void *_LIBC_SIZE(__smax) __s, rsize_t __smax, int __c, rsize_t __n) __OSX_AVAILABLE_STARTING(__MAC_10_9, __IPHONE_7_0);
__END_DECLS
#endif
```

**Comment by lingol** [comment]
Anyway I have rollback part of the changes around it. You can verify it by pinning MMKVCore to dev branch in your Podfile.

```ruby
pod 'MMKVCore', :git => 'https://github.com/Tencent/MMKV.git', :branch => 'dev'
```

**Comment by YueLiXing** [comment]
```
/Documents/workspace3/MallApp/ios/Pods/MMKVCore/Core/aes/AESCrypt.cpp:83:11: error: use of undeclared identifier 'memset_s'
   83 |     (void)memset_s(ptr, len, 0, len);
      |           ^
1 error generated.
```

same problem

**Comment by lingol** [comment]
That line suggested that you have **NOT** pin the source to the dev branch because `memset_s()` it's no longer called there. Maybe you should pin MMKV to dev as well? @YueLiXing

**Comment by forimbajosh21** [comment]
> That's strange. How does the file look around line 176 in your iOS SDK's `usr/include/_string.h`? It should looks like this, which provides `memset_s()`.
> 
> /* C11 Annex K */
> 
> #if defined(__STDC_WANT_LIB_EXT1__) && __STDC_WANT_LIB_EXT1__ >= 1
> #include <sys/_types/_rsize_t.h>
> #include <sys/_types/_errno_t.h>
> 
> __BEGIN_DECLS
> errno_t	memset_s(void *_LIBC_SIZE(__smax) __s, rsize_t __smax, int __c, rsize_t __n) __OSX_AVAILABLE_STARTING(__MAC_10_9, __IPHONE_7_0);
> __END_DECLS
> #endif

Thanks for looking into it! I checked, and the SDK header is exactly as you describe `iPhoneOS26.0.sdk/usr/include/_string.h` line 176:

```cpp
/* C11 Annex K */

#if defined(__STDC_WANT_LIB_EXT1__) && __STDC_WANT_LIB_EXT1__ >= 1
#include <sys/_types/_rsize_t.h>
#include <sys/_types/_errno_t.h>

__BEGIN_DECLS
errno_t	memset_s(void *_LIBC_SIZE(__smax) __s, rsize_t __smax, int __c, rsize_t __n) __OSX_AVAILABLE_STARTING(__MAC_10_9, __IPHONE_7_0);
__END_DECLS
#endif
```

One thing I noticed in the failing build log, in case it helps: CocoaPods compiles `AESCrypt.cpp` as Objective-C++ with a prefix header injected before the file:

```
clang -x objective-c++ ... -include "Pods/Target Support Files/MMKVCore/MMKVCore-prefix.pch" ... -c Pods/MMKVCore/Core/aes/AESCrypt.cpp
```

and the CocoaPods-generated `MMKVCore-prefix.pch` contains:

```objc
#ifdef __OBJC__
#import <UIKit/UIKit.h>
#else
...
#endif
```

Not sure if it's related, but that prefix header gets processed before the `#define __STDC_WANT_LIB_EXT1__ 1` at the top of `AESCrypt.cpp`.

Setup: CocoaPods with `use_frameworks! :linkage => :static`, Xcode 26.0, installed via react-native-mmkv. Happy to test a fix or provide the full build log if useful.

**Comment by YueLiXing** [comment]
> That line suggested that you have **NOT** pin the source to the dev branch because `memset_s()` it's no longer called there. Maybe you should pin MMKV to dev as well? 那句话表明，你并没有将源代码指向开发分支，因为现在它已经不再被称为开发分支了。也许你也应该将 MMKV 也指向开发分支呢？[@YueLiXing](https://github.com/YueLiXing)

```
pod 'MMKV', '2.4.0'
pod 'MMKVCore', '2.4.0'
```
build success

**Comment by lingol** [comment]
Anyone tried this? So far there's duplicated report telling v2.4.1 not OK and v2.4.0 OK, which I already get it.
@YueLiXing @forimbajosh21
```ruby
pod 'MMKVCore', :git => 'https://github.com/Tencent/MMKV.git', :branch => 'dev'
pod 'MMKV', :git => 'https://github.com/Tencent/MMKV.git', :branch => 'dev'
```

**Comment by YueLiXing** [comment]
> Anyone tried this? So far there's duplicated report telling v2.4.1 not OK and v2.4.0 OK, which I already get it.有人试过这个吗？目前有重复的报告称 v2.4.1 版本存在问题，而 v2.4.0 版本则没有问题。我已经明白了这一点。 [@YueLiXing](https://github.com/YueLiXing) [@forimbajosh21](https://github.com/forimbajosh21)
> 
> pod 'MMKVCore', :git => 'https://github.com/Tencent/MMKV.git', :branch => 'dev'
> pod 'MMKV', :git => 'https://github.com/Tencent/MMKV.git', :branch => 'dev'

build success

**Comment by lingol** [comment]
That's good to know. @YueLiXing 
A hotfix version will be release as soon as possible, wait till I get additional info from #1676

**Comment by claudesortwell** [comment]
Can confirm I was also having this issue and the commit also fixed my issue

**Comment by lingol** [comment]
It's fixed in [v2.4.2](https://github.com/Tencent/MMKV/releases/tag/v2.4.2).
